---
# tasks file for nginx
- name: Install EPEL
  yum:
    name: epel-release
    update_cache: yes
    state: latest
  when: ansible_distribution == 'CentOS'
  tags:
    - install-epel

# - name: Fix broken
#  shell: "apt --fix-broken install -y"
#  when: ansible_distribution == 'Debian'

- name: Install Nginx
  package:
    name: nginx
    state: latest
    update_cache: yes
  tags:
    - install-nginx

# - name: Restart nginx
#  service:
#    name: nginx
#    state: restarted
#  notify: Check HTTP Service
#  tags:
#    - always
